# Generated by Django 5.2.6 on 2025-09-21 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Контент')),
            ],
        ),
        migrations.RemoveField(
            model_name='department',
            name='description',
        ),
        migrations.RemoveField(
            model_name='program',
            name='coordinator',
        ),
        migrations.RemoveField(
            model_name='program',
            name='short_description',
        ),
        migrations.AddField(
            model_name='program',
            name='coordinator_contact',
            field=models.CharField(default='не вказано', max_length=100, verbose_name='Контакт координатора набору'),
        ),
        migrations.AddField(
            model_name='program',
            name='coordinator_name',
            field=models.CharField(default='не вказано', max_length=100, verbose_name='Імʼя координатора набору'),
        ),
        migrations.AddField(
            model_name='program',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='main.department', verbose_name='Випускова кафедра'),
        ),
        migrations.AddField(
            model_name='program',
            name='description',
            field=models.TextField(default='не вказано', verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='program',
            name='disciplines',
            field=models.TextField(default='не вказано', verbose_name='Список дисциплін (через кому)'),
        ),
        migrations.AlterField(
            model_name='department',
            name='head',
            field=models.CharField(max_length=100, verbose_name='Завідувач кафедри'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва кафедри'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='degree',
            field=models.CharField(max_length=100, verbose_name='Ступінь'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturers', to='main.department', verbose_name='Кафедра'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Імʼя'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='position',
            field=models.CharField(max_length=100, verbose_name='Посада'),
        ),
        migrations.AlterField(
            model_name='program',
            name='code',
            field=models.CharField(default='не вказано', max_length=15, verbose_name='Код спеціальності'),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(default='не вказано', max_length=100, verbose_name='Назва спеціальності'),
        ),
    ]
